### PR TITLE
Fix 404 error when refresh

### PR DESCRIPTION
**Pull request by ORuban**
the idea is to use HashLocationStrategy  as LocationStrategy and changes are based on [Angular 2 : 404 error occur when i refresh through Browser](http://stackoverflow.com/q/35284988/2833802) SO.

Remark: removing in `Startup` class is not related directly to fix, but this logic will be unuseful if add HashLocationStrategy.

### CODE REVIEW

**Comment by damienbod** [comment]
HI @ORuban 

Thanks for the pull request.

The solution doesn't have a refresh problem on the defined routes in the Startup class for the client application. I see that I need to add the '/about' route to the client side routing. I prefer clean urls to hash routing.  Microsoft JavascriptServices also have a middleware solution for this, maybe its a bit better.

I like your solution, and it removes to need for the middleware client routing on the server. 

I suggest we add this solution to the documentation and fix the /about route without integrating this pull request.

Opionions? @ORuban @FabianGosebrink @robisim74 

Greetings and thanks Damien

**Comment by robisim74** [comment]
Hi,

this is the official position of Angular Team: https://angular.io/docs/ts/latest/guide/router.html#!#browser-url-styles.

To fix the problem on the refresh, we have to change in Startup.cs this:

```
            var angularRoutes = new[] {
                 "/home"
             };
```
to this:

```
            var angularRoutes = new[] {
                 "/home",
                 "/about"
             };
```

Router on the server must match the router on the client.

@damienbod if you agree, immediately I solve the problem (and I adopt this solution also for my app...)

**Comment by damienbod** [comment]
I agree, I will also update the docs to explain the hash routing and how this could be implemented. I will not integrate this pull request then.

@ORuban I really appreciate the pull request, thanks a million, hope you understand our reasoning

Greetings Damien

**Comment by robisim74** [comment]
@damienbod I added the commit that fixes the error.

@ORuban thanks for the reporting.

Greetings

**Comment by ORuban** [comment]
Thanks, this is clear and make sense. Actually I also tried to simply add  "/about" and that only partially worked - when I did refresh on "/about" page, I was redirected to home page, but now I have re-checked and found that that was due to another problem in my custom middleware. So yes,  adding "/about" is a solution definitely. 

Happy to close this PR and thank you guys for your time.

**Comment by damienbod** [comment]
great thanks 

Greetings Damien

**Pull request closed without merging**
